<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SystemToolkit.Core\SystemToolkit.Core.csproj" />
    <ProjectReference Include="..\SystemToolkit.Infrastructure\SystemToolkit.Infrastructure.csproj" />
  </ItemGroup>

</Project>
